name: Project CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: make build
      - name: Install with Gradle
        run: make install